package com.siran.itemExchange.dataObjects;
// Generated Aug 17, 2026, 10:57:36 PM by Hibernate Tools 7.4.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name="categories"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Categories  implements java.io.Serializable {


    private Integer id;
    private String name;
    private Set<Listings> listingses = new HashSet<Listings>(0);

    public Categories() {
    }

	
    public Categories(String name) {
        this.name = name;
    }
    public Categories(String name, Set<Listings> listingses) {
       this.name = name;
       this.listingses = listingses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categories")
    public Set<Listings> getListingses() {
        return this.listingses;
    }
    
    public void setListingses(Set<Listings> listingses) {
        this.listingses = listingses;
    }




}


