package com.siran.itemExchange.dataObjects;
// Generated Aug 17, 2026, 10:57:36 PM by Hibernate Tools 7.4.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Listings generated by hbm2java
 */
@Entity
@Table(name="listings"
)
public class Listings  implements java.io.Serializable {


    private Integer id;
    private Categories categories;
    private Users users;
    private String title;
    private String description;
    private String listingType;
    private BigDecimal price;
    private String conditionGrade;
    private String status;
    private String imageUrl;
    private Date createdAt;
    private Date updatedAt;
    private Set<ListingPaymentMethods> listingPaymentMethodses = new HashSet<ListingPaymentMethods>(0);
    private Set<Messages> messageses = new HashSet<Messages>(0);
    private Set<Meetups> meetupses = new HashSet<Meetups>(0);

    public Listings() {
    }

	
    public Listings(Users users, String title, String listingType, String conditionGrade, String status) {
        this.users = users;
        this.title = title;
        this.listingType = listingType;
        this.conditionGrade = conditionGrade;
        this.status = status;
    }
    public Listings(Categories categories, Users users, String title, String description, String listingType, BigDecimal price, String conditionGrade, String status, String imageUrl, Date createdAt, Date updatedAt, Set<ListingPaymentMethods> listingPaymentMethodses, Set<Messages> messageses, Set<Meetups> meetupses) {
       this.categories = categories;
       this.users = users;
       this.title = title;
       this.description = description;
       this.listingType = listingType;
       this.price = price;
       this.conditionGrade = conditionGrade;
       this.status = status;
       this.imageUrl = imageUrl;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.listingPaymentMethodses = listingPaymentMethodses;
       this.messageses = messageses;
       this.meetupses = meetupses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id")
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="title", nullable=false, length=150)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="listing_type", nullable=false, length=8)
    public String getListingType() {
        return this.listingType;
    }
    
    public void setListingType(String listingType) {
        this.listingType = listingType;
    }

    
    @Column(name="price", precision=10, scale=2)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="condition_grade", nullable=false, length=8)
    public String getConditionGrade() {
        return this.conditionGrade;
    }
    
    public void setConditionGrade(String conditionGrade) {
        this.conditionGrade = conditionGrade;
    }

    
    @Column(name="status", nullable=false, length=9)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="image_url", length=500)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="listings")
    public Set<ListingPaymentMethods> getListingPaymentMethodses() {
        return this.listingPaymentMethodses;
    }
    
    public void setListingPaymentMethodses(Set<ListingPaymentMethods> listingPaymentMethodses) {
        this.listingPaymentMethodses = listingPaymentMethodses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="listings")
    public Set<Messages> getMessageses() {
        return this.messageses;
    }
    
    public void setMessageses(Set<Messages> messageses) {
        this.messageses = messageses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="listings")
    public Set<Meetups> getMeetupses() {
        return this.meetupses;
    }
    
    public void setMeetupses(Set<Meetups> meetupses) {
        this.meetupses = meetupses;
    }




}


