package com.siran.itemExchange.dataObjects;
// Generated Aug 17, 2026, 10:57:36 PM by Hibernate Tools 7.4.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * ListingPaymentMethods generated by hbm2java
 */
@Entity
@Table(name="listing_payment_methods"
    , uniqueConstraints = @UniqueConstraint(columnNames={"listing_id", "method"}) 
)
public class ListingPaymentMethods  implements java.io.Serializable {


    private int id;
    private Listings listings;
    private String method;

    public ListingPaymentMethods() {
    }

    public ListingPaymentMethods(int id, Listings listings, String method) {
       this.id = id;
       this.listings = listings;
       this.method = method;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="listing_id", nullable=false)
    public Listings getListings() {
        return this.listings;
    }
    
    public void setListings(Listings listings) {
        this.listings = listings;
    }

    
    @Column(name="method", nullable=false, length=6)
    public String getMethod() {
        return this.method;
    }
    
    public void setMethod(String method) {
        this.method = method;
    }




}


