package com.siran.itemExchange.dataObjects;
// Generated Aug 17, 2026, 10:57:36 PM by Hibernate Tools 7.4.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.Date;

/**
 * Meetups generated by hbm2java
 */
@Entity
@Table(name="meetups"
)
public class Meetups  implements java.io.Serializable {


    private Integer id;
    private Listings listings;
    private Users usersBySellerId;
    private Users usersByBuyerId;
    private String location;
    private Date proposedTime;
    private String status;
    private String notes;
    private Date createdAt;

    public Meetups() {
    }

	
    public Meetups(Listings listings, Users usersBySellerId, Users usersByBuyerId, String location, String status) {
        this.listings = listings;
        this.usersBySellerId = usersBySellerId;
        this.usersByBuyerId = usersByBuyerId;
        this.location = location;
        this.status = status;
    }
    public Meetups(Listings listings, Users usersBySellerId, Users usersByBuyerId, String location, Date proposedTime, String status, String notes, Date createdAt) {
       this.listings = listings;
       this.usersBySellerId = usersBySellerId;
       this.usersByBuyerId = usersByBuyerId;
       this.location = location;
       this.proposedTime = proposedTime;
       this.status = status;
       this.notes = notes;
       this.createdAt = createdAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="listing_id", nullable=false)
    public Listings getListings() {
        return this.listings;
    }
    
    public void setListings(Listings listings) {
        this.listings = listings;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="seller_id", nullable=false)
    public Users getUsersBySellerId() {
        return this.usersBySellerId;
    }
    
    public void setUsersBySellerId(Users usersBySellerId) {
        this.usersBySellerId = usersBySellerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="buyer_id", nullable=false)
    public Users getUsersByBuyerId() {
        return this.usersByBuyerId;
    }
    
    public void setUsersByBuyerId(Users usersByBuyerId) {
        this.usersByBuyerId = usersByBuyerId;
    }

    
    @Column(name="location", nullable=false, length=255)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="proposed_time", length=19)
    public Date getProposedTime() {
        return this.proposedTime;
    }
    
    public void setProposedTime(Date proposedTime) {
        this.proposedTime = proposedTime;
    }

    
    @Column(name="status", nullable=false, length=9)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="notes", length=65535)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


