package com.siran.itemExchange.dataObjects;
// Generated Aug 17, 2026, 10:57:36 PM by Hibernate Tools 7.4.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.Date;

/**
 * Messages generated by hbm2java
 */
@Entity
@Table(name="messages"
)
public class Messages  implements java.io.Serializable {


    private Integer id;
    private Listings listings;
    private Users usersByReceiverId;
    private Users usersBySenderId;
    private String content;
    private Boolean isRead;
    private Date createdAt;

    public Messages() {
    }

	
    public Messages(Listings listings, Users usersByReceiverId, Users usersBySenderId, String content) {
        this.listings = listings;
        this.usersByReceiverId = usersByReceiverId;
        this.usersBySenderId = usersBySenderId;
        this.content = content;
    }
    public Messages(Listings listings, Users usersByReceiverId, Users usersBySenderId, String content, Boolean isRead, Date createdAt) {
       this.listings = listings;
       this.usersByReceiverId = usersByReceiverId;
       this.usersBySenderId = usersBySenderId;
       this.content = content;
       this.isRead = isRead;
       this.createdAt = createdAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="listing_id", nullable=false)
    public Listings getListings() {
        return this.listings;
    }
    
    public void setListings(Listings listings) {
        this.listings = listings;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="receiver_id", nullable=false)
    public Users getUsersByReceiverId() {
        return this.usersByReceiverId;
    }
    
    public void setUsersByReceiverId(Users usersByReceiverId) {
        this.usersByReceiverId = usersByReceiverId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sender_id", nullable=false)
    public Users getUsersBySenderId() {
        return this.usersBySenderId;
    }
    
    public void setUsersBySenderId(Users usersBySenderId) {
        this.usersBySenderId = usersBySenderId;
    }

    
    @Column(name="content", nullable=false, length=65535)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="is_read")
    public Boolean getIsRead() {
        return this.isRead;
    }
    
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


