package com.siran.itemExchange.dataObjects;
// Generated Aug 17, 2026, 10:57:36 PM by Hibernate Tools 7.4.5.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="username")} 
)
public class Users  implements java.io.Serializable {


    private Integer id;
    private String username;
    private String password;
    private String email;
    private String phone;
    private String college;
    private Date createdAt;
    private Date updatedAt;
    private Set<Listings> listingses = new HashSet<Listings>(0);
    private Set<Meetups> meetupsesForSellerId = new HashSet<Meetups>(0);
    private Set<Messages> messagesesForReceiverId = new HashSet<Messages>(0);
    private Set<Messages> messagesesForSenderId = new HashSet<Messages>(0);
    private Set<Meetups> meetupsesForBuyerId = new HashSet<Meetups>(0);

    public Users() {
    }

	
    public Users(String username, String password, String email) {
        this.username = username;
        this.password = password;
        this.email = email;
    }
    public Users(String username, String password, String email, String phone, String college, Date createdAt, Date updatedAt, Set<Listings> listingses, Set<Meetups> meetupsesForSellerId, Set<Messages> messagesesForReceiverId, Set<Messages> messagesesForSenderId, Set<Meetups> meetupsesForBuyerId) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.phone = phone;
       this.college = college;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.listingses = listingses;
       this.meetupsesForSellerId = meetupsesForSellerId;
       this.messagesesForReceiverId = messagesesForReceiverId;
       this.messagesesForSenderId = messagesesForSenderId;
       this.meetupsesForBuyerId = meetupsesForBuyerId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", unique=true, nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=255)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", unique=true, nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="college", length=100)
    public String getCollege() {
        return this.college;
    }
    
    public void setCollege(String college) {
        this.college = college;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Listings> getListingses() {
        return this.listingses;
    }
    
    public void setListingses(Set<Listings> listingses) {
        this.listingses = listingses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usersBySellerId")
    public Set<Meetups> getMeetupsesForSellerId() {
        return this.meetupsesForSellerId;
    }
    
    public void setMeetupsesForSellerId(Set<Meetups> meetupsesForSellerId) {
        this.meetupsesForSellerId = meetupsesForSellerId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usersByReceiverId")
    public Set<Messages> getMessagesesForReceiverId() {
        return this.messagesesForReceiverId;
    }
    
    public void setMessagesesForReceiverId(Set<Messages> messagesesForReceiverId) {
        this.messagesesForReceiverId = messagesesForReceiverId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usersBySenderId")
    public Set<Messages> getMessagesesForSenderId() {
        return this.messagesesForSenderId;
    }
    
    public void setMessagesesForSenderId(Set<Messages> messagesesForSenderId) {
        this.messagesesForSenderId = messagesesForSenderId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usersByBuyerId")
    public Set<Meetups> getMeetupsesForBuyerId() {
        return this.meetupsesForBuyerId;
    }
    
    public void setMeetupsesForBuyerId(Set<Meetups> meetupsesForBuyerId) {
        this.meetupsesForBuyerId = meetupsesForBuyerId;
    }




}


